src/Entity/Articles.php
<?php

namespace App\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticlesRepository")
 * @Vich\Uploadable
 * @ORM\Table(name="articles")
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="You have to add a title!")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="You have to add the content of your article!")
     * @Assert\NotNull
     */
    private $text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * 
     * 0 = brouillon
     * 1 = en ligne
     * 
     * 
     * @ORM\Column(type="smallint")
     */
    private $active;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", 
     * mappedBy="article", orphanRemoval=true)
     */
    private $comments;


    // Près de la propriété $featured_image
    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $featured_image;

    /**
     * @Vich\UploadableField(mapping="featured_images", fileNameProperty="featuredImage")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", options={"default" : "CURRENT_TIMESTAMP"})
     * @var \DateTime
     */
    private $updatedAt;

     /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;


   
    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->date_creation = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->active = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getActive(): ?int
    {
        return $this->active;
    }

    public function setActive(int $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    // public function addComment(Comments $comment): self
    // {
    //     if (!$this->comments->contains($comment)) {
    //         $this->comments[] = $comment;
    //         $comment->setArticle($this);
    //     }

    //     return $this;
    // }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile(File $image=null)
    {
        $this->imageFile = $image;
        if($image) {
            $this->updatedAt = new \DateTime('now');    
        }
    }

    public function getFeaturedImage()
    {
        return $this->featured_image;
    }

    public function setFeaturedImage($featured_image)
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
    

}

src/Controller/BlogController.php
<?php

namespace App\Controller;
use App\Entity\Articles;
use App\Entity\Comments;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ArticlesRepository;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;

use App\Form\ArticlesType;


class BlogController extends AbstractController
{
    #[Route('/admin/create_article/{slug}', name: 'create_article', methods: ['GET', 'POST'])]
    public function create_article(EntityManagerInterface $em, $slug = null, ArticlesRepository $articlesRepo, Request $request): Response
    {
        // $hasAccess = $this->isGranted('ROLE_ADMIN');
        // $this->denyAccessUnlessGranted('ROLE_ADMIN');
        
        // if(!$hasAccess) {
        //     throw new \Exception("vous n'avez pas acces.");
        // }
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if(!$slug) {
            $article = new Articles();

            // $article->setTitle('title');
            // $em->persist($article);
            // $em->flush();

            // echo $article->getSlug();

            $nouveau = true;
        } else{
            $article = $articlesRepo->find($slug);
            if(!$article) {
                $this->addFlash('danger', "Cet article n'a pas été trouvé");
                return $this->redirectToRoute('blog');
            }
            $nouveau = false;
            $article->setUpdatedAt(new \DateTime());
        }
        
        //SUPPRIMER UN ARTICLE
        $action = $request->query->get('action');
        if ($action && $action == 'delete') {
            $em->remove($article);
            $em->flush();

            $this->addFlash('warning', "L'article a bien été supprimé.");
            return $this->redirectToRoute('blog');
        }

        $form = $this->createForm(ArticlesType::class, $article);
        
        $form->handleRequest($request);
            if($form->isSubmitted() && $form->isValid()){

                
                // upload image sans Vich
                // $image = $form->get('featured_image')->getData();
                // if($image){
                //     $fileName = 'normal'.md5(uniqid()).'.'.$image->guessExtension();
                //     $image->move(
                //         $this->getParameter('_images_directory'),
                //         $fileName
                //     );
                //     $article->setFeaturedImage($fileName);
                // }


                // if($nouveau) {
                //     $article
                //     ->setFeaturedImage($fichier)
                //     ->setDateCreation( new \DateTime() )
                //     ->setActive(1)
                //     ;
                // }
                if ($nouveau) {
                    $article->setDateCreation(new \DateTime())->setActive(1);
                }

                $em->persist($article);
                $em->flush();

                $this->addFlash('success', "L'article ete bien". ($nouveau ? ' créé' : 'modifié') .".");
                return $this->redirectToRoute('create_article', [
                    'id' => $article->getId(),
                    'slug' => $article->getSlug(),
                ] );
            }

        return $this->render('admin/create_article.html.twig', [
            'form' =>$form->createView(),
            'nouveau'=>$nouveau,
            'article'=>$article
        ]);
    }

    #[Route('/article/{slug}', name: 'article', methods: ['GET', 'POST'])]
    public function article($slug, Request $request, ArticlesRepository $articlesRepo, EntityManagerInterface $em): Response
    {
//        $articlesRepo = $em->getRepository(Articles::class);

        // $active == 1
        $article = $articlesRepo->findOneBySlug($slug);

        if (!$article) {
            $this->addFlash('danger', "L'article demandé n'a pas été trouvé");
            return $this->redirectToRoute('articles');    
        }

        //supprimer un commentaire
        $action = $request->query->get('action');
        if ($action && $action == 'delete') { 

            $id_comment = $request->query->get('id_comment');
            if($id_comment){
                $commentsRepo = $em->getRepository(Comments::class);
                $comment = $commentsRepo->find($id_comment);

//                $em->remove($comment);
//                $em->flush();
                if ($comment) {
                    $em->remove($comment);
                    $em->flush();
                    $this->addFlash('warning', "Le commentaire a bien été supprimé.");
                }
            
                return $this->redirectToRoute('article' , ['id' => $article->getId() ]);
            }
        }

        if($request->isMethod('POST')) {
            $data = $request->request->all();
            $comment = (new Comments())
                ->setArticle( $article )
                ->setAuthor( $data['author'])
                ->setEmail( $data['email'])
                ->setComment( $data['comment'])
                ->setDateCreation( new \DateTime() )
                ;

            $em->persist($comment);
            $em->flush();

            //$this->addFlash('success', "Your comment has been published!");
            //_fragment helps to get me back to the newly created comment once posted
            return $this->redirectToRoute('article', [
                'slug' => $article->getSlug(),
                '_fragment' => 'comment-'.$comment->getId()
            ]);
        }

        $postId = $request->get('slug');
        $post = $em->getRepository(Articles::class)->findOneBySlug($postId);
//        $recentArticles = $em->getRepository(Articles::class)->getRecentArticles($post->getSlug());

        $recentArticles = $articlesRepo->getRecentArticles($article->getSlug());
        return $this->render('blog/article.html.twig', [
            'article' => $article,
            'post'=> $post,
            'recentArticles'=> $recentArticles,
            'slug'=>$slug
        ]);
            
     }

    #[Route('/articles', name: 'articles', methods: ['GET'])]
    public function articles( Request $request, ArticlesRepository $articlesRepo, PaginatorInterface $paginator, EntityManagerInterface $em): Response
    {
//        $donnees = $this->getDoctrine()->getRepository(Articles::class)->findBy(array('active'=> 1));
        $donnees = $articlesRepo->findBy(['active' => 1]);
        $articles = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            4 // Nombre de résultats par page
        );
        return $this->render('blog/articles.html.twig', [
            'articles' => $articles,
        ]);
    }
}
    

templates/blog/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}Yom Blog - {{article.title}} {% endblock %}
{% block description %}{{{{ article.text|striptags|length > 300 ? article.text|striptags|easyadmin_truncate(300, true, "...")|raw  : article.text|striptags|raw }}}}{% endblock %}

{% block facebook %}
    <meta property="og:locale" content="en_US">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ article.title }}">
    <meta property="og:description" content="{{ article.text|striptags|length > 300 ? article.text|striptags|easyadmin_truncate(300, true, "...")|raw  : article.text|striptags|raw }}">
    <meta property="og:url" content="{{ path('article',{ slug: article.slug }) }}">
    <meta property="og:site_name" content="YOM - yoga on/off the mat">
    <meta property="fb:app_id" content="259443575421830" />
{% endblock %}

{% block ogimage %}
    <meta property="og:image" content="{{ vich_uploader_asset(article, 'imageFile') }}">
{% endblock ogimage %}

{% block body %}

    <!-- inner page banner END -->
    <div class="content-area bg-white">
        <div class="container ">
            <div class="row">
                <!-- Left part start -->
                <div class="col-lg-9 col-md-8">
                    <!-- blog start -->
                    <div class="blog-post blog-single">
                        <div class="dlab-post-title ">
                            <h1 class="post-title m-t0 text-center"><a href="#">{{article.title}}</a></h1>
                        </div>
                        <div class="dlab-post-meta m-b20 text-center">
                            <ul>
                                <li class="post-date"> <i class="ti-calendar"></i><strong>{{ article.dateCreation|date('d/m/Y')}}</strong> </li>
                                <li class="post-author"><i class="ti-user"></i>By <a href="#">{{ article.author}}</a> </li>
                                <li class="post-comment"><i class="ti-comment-alt"></i> <a href="#">{{ article.getComments|length }}</a> </li>
                            </ul>
                        </div>
                        
                        <div class="dlab-post-media dlab-img-effect"> <a href="#"><img src="{{ vich_uploader_asset(article, 'imageFile') }}" alt="Image"></a> </div>
                        <div class="dlab-post-text">
                            <p>{{ article.text|raw   }}</p>   
                        </div>
                        <!--Facebook share button-->
                        <div class="fb-share-button" data-href="{{ path('article',{ slug: article.slug }) }}" data-layout="button_count" data-size="small">
                            <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.yom-yoga.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a>
                        </div>
                    </div>

                    <div class="clear" id="comment-list">
                        <div class="comments-area" id="comments">
                            <h2 class="comments-title">Comments</h2>
                            <div class="clearfix">
                                {% for comment in article.comments %}
                                <ol class="comment-list">
                                    <li class="comment" id="comment-{{ comment.id }}">
                                        <div class="comment-body">
                                            <div class="comment-author vcard"> 
                                                <!-- <img  class="avatar photo" src="{{ asset('images/testimonials/pic1.jpg') }}" alt=""> -->
                                                <cite class="fn"> {{ comment.author}}</cite> <span class="says">says:</span> </div>
                                                <div class="comment-meta"> <a href="#">{{ comment.dateCreation|date('d/m/Y') }}</a> </div>
                                                <p>{{ comment.comment }} </p>
                                                {# <div class="reply"> <a href="#respond" class="comment-reply-link">Reply</a> </div> #}
                                        </div>
                                    </li>
                                </ol>
                                {% endfor %}
                                <!-- comment list END -->
                                <!-- Form -->
                                <div class="comment-respond mb-5" id="respond">
                                    <h4 class="comment-reply-title" id="reply-title">Leave a Reply  </h4>
                                    <form class="comment-form" id="commentform" method="post" >
                                        <p class="comment-form-author">
                                            <label for="author">Name</label>
                                            <input type="text" required class="form-control" name="author"  placeholder="Author" id="author">
                                        </p>
                                        <p class="comment-form-email">
                                            <label for="email">Email</label>
                                            <input type="text" required class="form-control" placeholder="Email" name="email" id="email">
                                        </p>
                                        <p class="comment-form-comment">
                                            <label for="comment">Comment</label>
                                            <textarea rows="8" required class="form-control" name="comment" placeholder="comment" id="comment"></textarea>
                                        </p>
                                        <p class="form-submit">
                                        <label for="submit">Send</label>
                                            <input type="submit" class="submit" id="submit" name="submit" value="post comment">
                                        </p>
                                    </form>
                                </div>
                                <!-- Form -->
                            </div>
                        </div>
                    </div>
                    <!-- blog END -->
                </div>
                <!-- Left part END -->
                <!-- Side bar start -->
                
               
                <div class="col-lg-3 col-md-4 sticky-top pt-4">
                    <aside  class="side-bar">
                        <div class="widget recent-posts-entry">
                            <h6 class="widget-title style-1">Recent Posts</h6>
                            {# {% for recentPost in 1..3 %} #}
                            {% for recentPost in recentArticles %}
                            {# {% for recentPost in recentArticles if recentPost.id != article.id %} #}
                            <div class="widget-post-bx">
                                <div class="widget-post clearfix">
                                    <div class="dlab-post-media"> <img src="{{ vich_uploader_asset(recentPost, 'imageFile')|imagine_filter('carre')  }}"  alt="{{ recentPost.title }}"> </div>
                                    
                                    <div class="dlab-post-info">
                                        <div class="dlab-post-header">
                                        
                                            <h6 class="post-title"><a href="{{ path('article', {slug:recentPost.slug}) }}">{{recentPost.title}}</a></h1></h6>
                                        </div>
                                        <div class="dlab-post-meta">
                                            <ul>
                                                <li class="post-author">By {{recentPost.author}}</li>
                                                <li class="post-comment"><i class="ti-comment-alt"></i>{{ recentPost.getComments|length }}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {# {% endfor %} #}
                            {% endfor %}
                        </div>
                    </aside>
                </div>
                <!-- Side bar END -->
            </div>
        </div>
    </div>

<!-- Content END-->
{% endblock %}

templates/blog/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Yom Yoga blog{% endblock %}
{% block description %}Yom blog articles available to everyone.{% endblock %}

{% block body %}
    <div class="content-area">
    <h1 class="text-dark text-center pb-5">NOTES</h1>
        <div class="container">
            <div class="row">
                <!-- blog grid -->
                <div id="masonry" class="dlab-blog-grid-2" style="width: 100%;">
                    {% for article  in articles %}
                
                    <div class="post card-container col-lg-6 col-md-6 col-sm-12">
                        <div class="blog-post blog-grid blog-rounded blog-effect1">
                            <div class="dlab-post-media dlab-img-effect" id="blogimage"> 
                                <a href="{{ path('article', {slug:article.slug}) }}"><img src="{{ vich_uploader_asset(article, 'imageFile') |imagine_filter('reduc') }}" alt="{{article.title}}"/></a> 
                            </div>
                            <div class="dlab-info p-a20 border-1">
                                <div class="dlab-post-title ">
                                    <h4 class="post-title"><a href=" {{ path('article', {slug:article.slug}) }}">{{article.title}}</a></h4>
                                </div>
                                <div class="dlab-post-meta ">
                                    <ul>
                                        <li class="post-date"> <i class="ti-calendar"></i><strong>{{article.dateCreation|date('d/m/Y')}}</strong> </li>
                                        <li class="post-author"><i class="ti-user"></i>By <a href="#">{{article.author}}</a> </li>
                                        <li class="post-comment"><i class="ti-comment-alt"></i> <a href="#">{{ article.getComments|length }}</a> </li>
                                    </ul>
                                </div>
                                <div class="dlab-post-text">
                                    <p>{{ article.text|striptags|length > 300 ? article.text|striptags|easyadmin_truncate(300, true, "...")|raw  : article.text|striptags|raw }}</p>
                                    {# <p>{{ (article.text|length > 300 ? article.text|striptags|slice(0, 300) ~ '…' : article.text)  }}</p> #}
                                </div>
                                <div class="dlab-post-readmore blog-share"> 
                                    <a href=" {{ path('article', {slug:article.slug}) }}" title="READ MORE" rel="bookmark" class="site-button outline outline-2">READ MORE
                                        <i class="ti-arrow-right"></i>
                                    </a>
                                    <div class="share-btn">
                                        <ul class="clearfix">
                                            <li><a href="https://www.instagram.com/liveyomlife/" target="_blank" class="site-button sharp"><i class="fa fa-facebook"></i></a></li>
                                            <li><a href="https://www.facebook.com/liveyomlife/" target="_blank" class="site-button sharp"><i class="fa fa-instagram"></i></a></li>
                                            <li><a href="#" class="site-button sharp" target="_blank"><i class="fa fa-youtube"></i></a></li>
                                            <li class="share-button"><a href="#" target="_blank" class="site-button sharp"><i class="fa fa-share-alt"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}  
                </div>
                <!-- blog grid END -->
                
                <!-- Pagination start -->
                <div class="pagination-bx clearfix  col-md-12 text-center">
                    <ul class="pagination">
                        <div class="navigation">
                            {{ knp_pagination_render(articles) }}
                        </div>
                    </ul>
                </div>
                <!-- Pagination END -->
            </div>
        </div>
    </div>
</div>
<!-- Content END-->
       
{% endblock %}

templates/blog/create_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}New article{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-2">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-home-tab"  href="{{ path('home') }}" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</a>
            <a class="nav-link" id="v-pills-addArticle-tab"  href="{{ path('create_article') }}" role="tab" aria-controls="v-pills-article" aria-selected="false">Add Article</a>
            <a class="nav-link" id="v-pills-messages-tab"  href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Messages</a>
            <a class="nav-link" id="v-pills-settings-tab"  href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
        </div>
    </div>

    <div class="col-10 section-full bg-white" id="contact">
        <div class="row dzseth">
            <div class="container bg-gray">
                <div class="section-head text-center">
                    <div class="container pt-5">
                        {% for label, messages in app.flashes %}
                            {% for message in messages %}
                                <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">x</span></button>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    </div>

                    {% if nouveau %}
                        <h2 class="text-uppercase  ">Create new article</h2>
                    {% else %}
                        <a href="{{ path('create_article', {id: article.id, action: 'delete'}) }} " class="text-danger float-right btn">Supprimer</a>
                        <h2 class="text-uppercase"> {{ article.title }}</h2>
                    {% endif %}
                    <div class="dlab-separator bg-primary "></div>
                </div>
            
                <div class="p-lr30 clearfix m-b30 contact-style-1">
                    {{ form(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote.min.js"></script>
    <script src="{{ asset('js/summernote.js') }}"></script>

{% endblock %}